[package]
name = "monitetoring"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap = "2.2.0"
etherparse = "0.14.0"
procfs = "0.16.0"
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
crossterm = "0.27"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
